/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_result$schema$value ??= z.object({
  'status': z.union([z.literal("cancelled"), z.literal("not-running"), z.literal("too-late")]).readonly(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_1$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_1$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_1$schema$value ??= z.union([z.undefined(), z.object({
  'registry': z.union([z.literal(null), z.string()]).readonly().optional(),
})]))
let _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_inspect_result$schema$value ??= z.union([z.object({
  'status': z.literal("accepted").readonly(),
  'kind': z.union([z.literal("registry"), z.literal("path"), z.literal("git"), z.literal("tarball")]).readonly(),
  'name': z.string().readonly().optional(),
  'version': z.string().readonly().optional(),
  'description': z.string().readonly().optional(),
  'bundle': z.union([z.literal(null), z.literal(false), z.literal(true)]).readonly(),
  'registry': z.union([z.literal(null), z.string()]).readonly(),
  'host': z.string().readonly().optional(),
}), z.object({
  'status': z.literal("refused").readonly(),
  'problem': z.union([z.literal("network"), z.literal("unknown"), z.literal("invalid-spec"), z.literal("not-found"), z.literal("already-installed"), z.literal("not-a-package"), z.literal("not-a-bundle")]).readonly(),
  'reason': z.string().readonly(),
  'registries': z.array(z.union([z.literal(null), z.string()])).readonly().optional(),
})]))
let _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_1$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_1$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_1$schema$value ??= z.union([z.undefined(), z.object({
  'enabled': z.boolean().optional(),
  'requestId': z.intersection(z.string(), z.unknown()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registry': z.union([z.literal(null), z.string()]).optional(),
})]))
let _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_result$schema$value ??= z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_listBundles_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_listBundles_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_listBundles_result$schema$value ??= z.array(z.object({
  'name': z.string(),
  'version': z.string().optional(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).optional(),
  'description': z.string().optional(),
  'enabled': z.boolean(),
  'installed': z.boolean(),
  'optional': z.boolean(),
  'removable': z.boolean(),
  'readOnlyReason': z.union([z.literal("management-required"), z.literal("unaddressable")]).optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'rows': z.array(z.object({
  'rowId': z.string(),
  'moduleName': z.string(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).optional(),
  'entryId': z.intersection(z.string(), z.unknown()).optional(),
})),
  'overrides': z.array(z.string()),
})))
let _deepseek_ai_dsh_plugin_manager_pluginManager_listPlugins_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_listPlugins_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_listPlugins_result$schema$value ??= z.array(z.union([z.intersection(z.object({
  'entryId': z.intersection(z.string(), z.unknown()).readonly(),
  'moduleName': z.string().readonly(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).readonly().optional(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
}), z.object({
  'patchId': z.string(),
  'readOnlyReason': z.never().optional(),
})), z.intersection(z.object({
  'entryId': z.intersection(z.string(), z.unknown()).readonly(),
  'moduleName': z.string().readonly(),
  'meta': z.object({
  'title': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'description': z.union([z.string(), z.intersection(z.object({
  'en': z.string().readonly(),
}), z.record(z.string(), z.string()).readonly())]).readonly().optional(),
  'icon': z.string().readonly().optional(),
  'error': z.string().readonly().optional(),
}).readonly().optional(),
  'enabled': z.boolean().readonly(),
  'fiberPhase': z.union([z.literal(null), z.literal("failed"), z.literal("pending"), z.literal("active"), z.literal("loading"), z.literal("unloading")]).readonly(),
}), z.object({
  'patchId': z.never().optional(),
  'readOnlyReason': z.union([z.literal("management-required"), z.literal("unaddressable")]),
}))])))
let _deepseek_ai_dsh_plugin_manager_pluginManager_listVersionExemptions_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_listVersionExemptions_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_listVersionExemptions_result$schema$value ??= z.object({
  'exemptions': z.record(z.string(), z.array(z.string())),
  'warnings': z.array(z.string()),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_registries_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_registries_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_registries_result$schema$value ??= z.object({
  'registry': z.union([z.literal(null), z.string()]).readonly(),
  'fallbackRegistries': z.array(z.string()).readonly(),
  'resolved': z.union([z.literal(null), z.string()]).readonly(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_result$schema$value ??= z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_1$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_1$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_1$schema$value ??= z.boolean())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_result$schema$value ??= z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_1$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_1$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_1$schema$value ??= z.boolean())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_result$schema$value ??= z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_0$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_1$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_1$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_1$schema$value ??= z.string())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_2$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_2$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_2$schema$value ??= z.boolean())
let _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_3$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_3$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_3$schema$value ??= z.union([z.undefined(), z.literal(false), z.literal(true)]))
let _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_result$schema$value ??= z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
}))
let _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_parameter_0$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_parameter_0$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_parameter_0$schema$value ??= z.intersection(z.string(), z.unknown()))
let _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_result$schema$value
const _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_result$schema = () => (_deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_result$schema$value ??= z.union([z.literal(null), z.object({
  'changed': z.boolean(),
  'application': z.union([z.literal("cancelled"), z.literal("failed"), z.literal("applied"), z.literal("restart-required"), z.literal("overridden")]),
  'stage': z.union([z.literal("remove"), z.literal("install"), z.literal("enable")]),
  'target': z.string(),
  'enabled': z.boolean().optional(),
  'error': z.object({
  'code': z.union([z.literal("management-required"), z.literal("unaddressable"), z.literal("unknown-plugin"), z.literal("invalid-spec"), z.literal("ambiguous-install"), z.literal("not-bundle"), z.literal("not-removable"), z.literal("stop-profile"), z.literal("bundle-in-use"), z.literal("stale-approval"), z.literal("incompatible-version"), z.literal("operation-error")]),
  'diagnostic': z.string().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'warnings': z.array(z.string()).optional(),
  'packageResult': z.object({
  'exitCode': z.number(),
  'output': z.string(),
  'truncated': z.boolean(),
  'logPath': z.string(),
  'kind': z.union([z.literal("network"), z.literal("unknown"), z.literal("timeout"), z.literal("integrity"), z.literal("pnpm-missing"), z.literal("not-found"), z.literal("no-matching-version"), z.literal("disk-full"), z.literal("permission"), z.literal("build-blocked")]).optional(),
  'timedOut': z.boolean().optional(),
  'incompatible': z.array(z.object({
  'name': z.string(),
  'version': z.string(),
  'runtimeVersion': z.string(),
  'peers': z.record(z.string(), z.string()),
})).optional(),
}).optional(),
  'bundle': z.string().optional(),
  'pendingBuilds': z.array(z.string()).optional(),
  'approvedBuilds': z.array(z.string()).optional(),
  'registries': z.array(z.union([z.literal(null), z.string()])).optional(),
  'failedAt': z.union([z.literal("registry"), z.literal("spec-host")]).optional(),
})]))

export const TYPERT = {
  package: '@deepseek-ai/dsh-plugin-manager',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/cancelInstall',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'cancelInstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'requestId',
          wire: 'requestId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#PluginInstallRequestId',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#PluginInstallCancellation',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_cancelInstall_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":585,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/inspect',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'inspect',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'spec',
          wire: 'spec',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/inspect:spec',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_0$schema,
          },
        },
        {
          name: 'options',
          wire: 'options',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#InspectOptions',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#PluginSpecInspection',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_inspect_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":341,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/installBundle',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'installBundle',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'spec',
          wire: 'spec',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/installBundle:spec',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_0$schema,
          },
        },
        {
          name: 'options',
          wire: 'options',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#InstallBundleOptions',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#ChangeResult',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_installBundle_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":462,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/listBundles',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'listBundles',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/listBundles:result',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_listBundles_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":280,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/listPlugins',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'listPlugins',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/listPlugins:result',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_listPlugins_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":256,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/listVersionExemptions',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'listVersionExemptions',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/listVersionExemptions:result',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_listVersionExemptions_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":232,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/registries',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'registries',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#PluginRegistries',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_registries_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":325,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/removeBundle',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'removeBundle',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/removeBundle:name',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#ChangeResult',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_removeBundle_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":601,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/setBundleEnabled',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'setBundleEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'name',
          wire: 'name',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setBundleEnabled:name',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_0$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setBundleEnabled:enabled',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#ChangeResult',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_setBundleEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":443,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/setPluginEnabled',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'setPluginEnabled',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-host-plugin-inventory/types#PluginEntryId',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_0$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setPluginEnabled:enabled',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#ChangeResult',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_setPluginEnabled_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":425,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/setVersionExemption',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'setVersionExemption',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'packageVersion',
          wire: 'packageVersion',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setVersionExemption:packageVersion',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_0$schema,
          },
        },
        {
          name: 'runtimeVersion',
          wire: 'runtimeVersion',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setVersionExemption:runtimeVersion',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_1$schema,
          },
        },
        {
          name: 'enabled',
          wire: 'enabled',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setVersionExemption:enabled',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_2$schema,
          },
        },
        {
          name: 'acceptRisk',
          wire: 'acceptRisk',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/setVersionExemption:acceptRisk',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_parameter_3$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#ChangeResult',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_setVersionExemption_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":245,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-manager#pluginManager/waitForInstall',
      service: 'pluginManager',
      namespace: 'pluginManager',
      method: 'waitForInstall',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'requestId',
          wire: 'requestId',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-manager/types#PluginInstallRequestId',
            create: _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-manager#pluginManager/waitForInstall:result',
        create: _deepseek_ai_dsh_plugin_manager_pluginManager_waitForInstall_result$schema,
      },
      sourceLocation: {"file":"packages/boot/plugin-manager/src/index.ts","line":575,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Manage profile files and apply their declared reload lifecycle.",
        "summary": "Manage profile files and apply their declared reload lifecycle.",
        "tags": [],
        "jsDoc": "/** Manage profile files and apply their declared reload lifecycle. */",
        "key": "pluginManager",
        "exportName": "PluginManager",
        "members": [
          {
            "kind": "method",
            "name": "listVersionExemptions",
            "signature": "@Remote listVersionExemptions(): { exemptions: Record<string, string[]>; warnings: string[] }",
            "summary": "Read exact plugin-version exemptions saved in this profile.",
            "jsDoc": "/** Read exact plugin-version exemptions saved in this profile.\n * @returns Accepted package-name@version keys with the runtime versions they may run on, and any\n * record or file problem the reader rejected, which the caller reports instead of failing.\n */"
          },
          {
            "kind": "method",
            "name": "setVersionExemption",
            "signature": "@Remote setVersionExemption(packageVersion: string, runtimeVersion: string, enabled: boolean, acceptRisk?: boolean): Promise<ChangeResult>",
            "summary": "Grant or revoke one exact plugin/runtime exemption and reevaluate live plugins.",
            "jsDoc": "/** Grant or revoke one exact plugin/runtime exemption and reevaluate live plugins.\n * @param packageVersion Exact manifest package name followed by @ and its version; never an installation spec or alias.\n * @param runtimeVersion Exact current DSH version for grants; revocation may name a previous runtime.\n * @param enabled Whether to grant rather than revoke the exemption.\n * @param acceptRisk Required true for grants after the user accepts possible crashes and data loss.\n * @returns Saved and runtime outcomes. Startup-only profiles require restart.\n */"
          },
          {
            "kind": "method",
            "name": "listPlugins",
            "signature": "@Remote async listPlugins(): Promise<PluginInfo[]>",
            "summary": "Read current plugins, including why a row cannot be changed through the profile patch.",
            "jsDoc": "/** Read current plugins, including why a row cannot be changed through the profile patch.\n * @returns Current runtime entries with persistent patch targets.\n */"
          },
          {
            "kind": "method",
            "name": "listBundles",
            "signature": "@Remote listBundles(): Promise<BundleInfo[]>",
            "summary": "Read the profile's installed bundles, the bundles this dsh installation supplies, and the selected names that are not bundles.",
            "jsDoc": "/** Read the profile's installed bundles, the bundles this dsh installation supplies, and the selected names that are not bundles.\n * A dependency without a bundle patch is listed, as a `not-bundle` problem, only while it is selected.\n * @returns Package versions, manifest descriptions, rows, optional display metadata, activation selections,\n * whether the installation offers the bundle, and removal availability.\n */"
          },
          {
            "kind": "method",
            "name": "registries",
            "signature": "@Remote async registries(): Promise<PluginRegistries>",
            "summary": "Read the registries this manager asks: the configured first one, its fallbacks in order, and what pnpm's own configuration names.",
            "jsDoc": "/** Read the registries this manager asks: the configured first one, its fallbacks in order, and what pnpm's own configuration names.\n * @returns The registries in pnpm's comparison form; null is the one pnpm's own configuration names, `resolved` as pnpm reads it now.\n */"
          },
          {
            "kind": "method",
            "name": "inspect",
            "signature": "@Remote async inspect(spec: string, options?: InspectOptions, signal?: AbortSignal): Promise<PluginSpecInspection>",
            "summary": "Read what a spec names before installing it.",
            "jsDoc": "/** Read what a spec names before installing it.\n * @param spec One package spec: a registry name, an absolute path, a git address, or a tarball.\n * @param options The registry asked first.\n * @param signal Ends a registry lookup early.\n * @returns The package the spec names, or why it is refused.\n */"
          },
          {
            "kind": "method",
            "name": "setPluginEnabled",
            "signature": "@Remote setPluginEnabled(id: PluginEntryId, enabled: boolean): Promise<ChangeResult>",
            "summary": "Persist a plugin entry's desired enablement and apply it on live profiles.",
            "jsDoc": "/** Persist a plugin entry's desired enablement and apply it on live profiles.\n * @param id Loader entry identity returned by listPlugins.\n * @param enabled Whether the plugin should run.\n * @returns Saved and runtime outcomes, including higher-priority overrides.\n */"
          },
          {
            "kind": "method",
            "name": "setBundleEnabled",
            "signature": "@Remote setBundleEnabled(name: string, enabled: boolean): Promise<ChangeResult>",
            "summary": "Select or remove a bundle layer while retaining installed dependencies.",
            "jsDoc": "/** Select or remove a bundle layer while retaining installed dependencies.\n * @param name Bundle package name.\n * @param enabled Whether the bundle contributes its patch layer.\n * @returns Persisted and runtime outcomes.\n */"
          },
          {
            "kind": "method",
            "name": "installBundle",
            "signature": "@Remote installBundle(spec: string, options?: InstallBundleOptions): Promise<ChangeResult>",
            "summary": "Install a package using the same pnpm implementation as dsh plugin.",
            "jsDoc": "/**\n * Install a package using the same pnpm implementation as dsh plugin. GitHub\n * repositories get a connection check bounded by githubConnectionTimeoutMs before pnpm starts;\n * only network failures or timeouts stop installation, while pnpm owns authentication and transport fallback. A run\n * that fails, is cancelled, or adds a package without a bundle patch restores\n * `package.json` and `pnpm-lock.yaml` as they were; downloaded files can stay.\n * @param spec One package spec, including local paths relative to the invocation directory.\n * @param options Whether to activate the installed bundle (defaults to true), the request id a cancellation names,\n * the pending build scripts to allow for this profile before pnpm runs, and the registry asked first.\n * @returns Package-manager diagnostics, the registries asked, and the observed activation outcome.\n */"
          },
          {
            "kind": "method",
            "name": "waitForInstall",
            "signature": "@Remote async waitForInstall(requestId: PluginInstallRequestId): Promise<ChangeResult | null>",
            "summary": "Recover the result of an active installation without cancelling it.",
            "jsDoc": "/** Recover the result of an active installation without cancelling it.\n * @param requestId The id supplied when installation started.\n * @returns The installation's outcome after it settles, or null if no active request has that id.\n * Completed results are not retained; null establishes neither success nor cancellation.\n */"
          },
          {
            "kind": "method",
            "name": "cancelInstall",
            "signature": "@Remote async cancelInstall(requestId: PluginInstallRequestId): Promise<PluginInstallCancellation>",
            "summary": "Stop an installation this manager owns and wait until its files are back.",
            "jsDoc": "/** Stop an installation this manager owns and wait until its files are back.\n * @param requestId The id the installation was started with.\n * @returns `cancelled` once the Git check or pnpm exited and the files are restored, `too-late` once the bundle is being\n * applied, `not-running` for any other id.\n */"
          },
          {
            "kind": "method",
            "name": "removeBundle",
            "signature": "@Remote removeBundle(name: string): Promise<ChangeResult>",
            "summary": "Unload and remove a profile-owned bundle dependency through dsh plugin's pnpm path.",
            "jsDoc": "/** Unload and remove a profile-owned bundle dependency through dsh plugin's pnpm path.\n * @param name Installed dependency name.\n * @returns Removal diagnostics and the remaining profile state.\n */"
          }
        ],
        "types": [
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "BundleInfo",
            "declaration": "export interface BundleInfo {\n    name: string;\n    version?: string;\n    meta?: PluginLocalizedMeta;\n    description?: string;\n    enabled: boolean;\n    installed: boolean;\n    optional: boolean;\n    removable: boolean;\n    readOnlyReason?: ReadOnlyReason;\n    error?: ManagementError;\n    rows: BundleRowInfo[];\n    overrides: string[];\n}"
          },
          {
            "name": "BundleRowInfo",
            "declaration": "export interface BundleRowInfo {\n    rowId: string;\n    moduleName: string;\n    meta?: PluginLocalizedMeta;\n    entryId?: PluginEntryId;\n}"
          },
          {
            "name": "ChangeResult",
            "declaration": "export interface ChangeResult {\n    changed: boolean;\n    application: 'applied' | 'restart-required' | 'overridden' | 'failed' | 'cancelled';\n    stage: 'install' | 'enable' | 'remove';\n    target: string;\n    enabled?: boolean;\n    error?: ManagementError;\n    warnings?: string[];\n    packageResult?: PackageResult;\n    bundle?: string;\n    pendingBuilds?: string[];\n    approvedBuilds?: string[];\n    registries?: Registry[];\n    failedAt?: 'registry' | 'spec-host';\n}"
          },
          {
            "name": "IncompatiblePlugin",
            "declaration": "export interface IncompatiblePlugin {\n    name: string;\n    version: string;\n    runtimeVersion: string;\n    peers: Record<string, string>;\n}"
          },
          {
            "name": "InspectOptions",
            "declaration": "export interface InspectOptions {\n    readonly registry?: Registry;\n}"
          },
          {
            "name": "InstallBundleOptions",
            "declaration": "export interface InstallBundleOptions {\n    enabled?: boolean;\n    requestId?: PluginInstallRequestId;\n    approvedBuilds?: string[];\n    registry?: Registry;\n}"
          },
          {
            "name": "InstallSpecKind",
            "declaration": "export type InstallSpecKind = 'registry' | 'path' | 'git' | 'tarball';"
          },
          {
            "name": "LocalizedText",
            "declaration": "export type LocalizedText = string | { readonly en: string; readonly [locale: string]: string; };"
          },
          {
            "name": "ManagementError",
            "declaration": "export interface ManagementError {\n    code: ReadOnlyReason | 'unknown-plugin' | 'invalid-spec' | 'ambiguous-install' | 'not-bundle' | 'not-removable' | 'stop-profile' | 'bundle-in-use' | 'stale-approval' | 'incompatible-version' | 'operation-error';\n    diagnostic?: string;\n    incompatible?: IncompatiblePlugin[];\n}"
          },
          {
            "name": "PackageResult",
            "declaration": "export interface PackageResult {\n    exitCode: number;\n    output: string;\n    truncated: boolean;\n    logPath: string;\n    kind?: PluginInstallFailureKind;\n    timedOut?: boolean;\n    incompatible?: IncompatiblePlugin[];\n}"
          },
          {
            "name": "PluginEntryId",
            "declaration": "export type PluginEntryId = Branded<'PluginEntryId'>;"
          },
          {
            "name": "PluginFiberPhase",
            "declaration": "export type PluginFiberPhase = 'pending' | 'loading' | 'active' | 'failed' | 'unloading' | null;"
          },
          {
            "name": "PluginInfo",
            "declaration": "export type PluginInfo = PluginInventoryEntry & ({ patchId: string; readOnlyReason?: never; } | { patchId?: never; readOnlyReason: ReadOnlyReason; });"
          },
          {
            "name": "PluginInspectProblem",
            "declaration": "export type PluginInspectProblem = 'invalid-spec' | 'already-installed' | 'not-found' | 'not-a-package' | 'not-a-bundle' | 'network' | 'unknown';"
          },
          {
            "name": "PluginInstallCancellation",
            "declaration": "export interface PluginInstallCancellation {\n    readonly status: 'cancelled' | 'too-late' | 'not-running';\n}"
          },
          {
            "name": "PluginInstallFailureKind",
            "declaration": "export type PluginInstallFailureKind = 'pnpm-missing' | 'timeout' | 'not-found' | 'no-matching-version' | 'network' | 'disk-full' | 'permission' | 'build-blocked' | 'integrity' | 'unknown';"
          },
          {
            "name": "PluginInstallRequestId",
            "declaration": "export type PluginInstallRequestId = Branded<'PluginInstallRequestId'>;"
          },
          {
            "name": "PluginInventoryEntry",
            "declaration": "export interface PluginInventoryEntry {\n    readonly entryId: PluginEntryId;\n    readonly moduleName: string;\n    readonly meta?: PluginLocalizedMeta;\n    readonly enabled: boolean;\n    readonly fiberPhase: PluginFiberPhase;\n}"
          },
          {
            "name": "PluginLocalizedMeta",
            "declaration": "export interface PluginLocalizedMeta {\n    readonly title?: LocalizedText;\n    readonly description?: LocalizedText;\n    readonly icon?: string;\n    readonly error?: string;\n}"
          },
          {
            "name": "PluginRegistries",
            "declaration": "export interface PluginRegistries {\n    readonly registry: Registry;\n    readonly fallbackRegistries: readonly string[];\n    readonly resolved: string | null;\n}"
          },
          {
            "name": "PluginSpecInspection",
            "declaration": "export type PluginSpecInspection = { readonly status: 'accepted'; readonly kind: InstallSpecKind; readonly name?: string; readonly version?: string; readonly description?: string; readonly bundle: boolean | null; readonly registry: Registry; readonly host?: string; } | { readonly status: 'refused'; readonly problem: PluginInspectProblem; readonly reason: string; readonly registries?: Registry[]; };"
          },
          {
            "name": "ReadOnlyReason",
            "declaration": "export type ReadOnlyReason = 'management-required' | 'unaddressable';"
          },
          {
            "name": "Registry",
            "declaration": "export type Registry = string | null;"
          }
        ]
      }
    ],
    "events": [
      {
        "description": "The profile's plugins, bundles, or composition changed: a manager operation completed. A patch generation applied outside the manager, by HMR's watcher after a CLI or hand edit, announces nothing here.",
        "summary": "The profile's plugins, bundles, or composition changed: a manager operation completed.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit\n     *"
          },
          {
            "name": "param",
            "argument": "change",
            "comment": "- what changed.",
            "text": "@param change - what changed."
          }
        ],
        "jsDoc": "/**\n * The profile's plugins, bundles, or composition changed: a manager\n * operation completed. A patch generation applied outside the manager,\n * by HMR's watcher after a CLI or hand edit, announces nothing here.\n * @mode emit\n * @param change - what changed.\n */",
        "name": "plugin-manager/changed",
        "mode": "emit",
        "signature": "'plugin-manager/changed'(change: PluginChange): void"
      },
      {
        "description": "One chunk of a pnpm run's output, streamed as the run produces it.",
        "summary": "One chunk of a pnpm run's output, streamed as the run produces it.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit\n     *"
          },
          {
            "name": "param",
            "argument": "chunk",
            "comment": "- the chunk and the run it belongs to.",
            "text": "@param chunk - the chunk and the run it belongs to."
          }
        ],
        "jsDoc": "/**\n * One chunk of a pnpm run's output, streamed as the run produces it.\n * @mode emit\n * @param chunk - the chunk and the run it belongs to.\n */",
        "name": "plugin-manager/install-log",
        "mode": "emit",
        "signature": "'plugin-manager/install-log'(chunk: PluginInstallLogChunk): void"
      },
      {
        "description": "An installation moved between its Host phases. `installing` is announced once per registry the installation asks, with the attempt's registry and position; `cancelling` and `applying` once.",
        "summary": "An installation moved between its Host phases.",
        "tags": [
          {
            "name": "mode",
            "comment": "emit",
            "text": "@mode emit\n     *"
          },
          {
            "name": "param",
            "argument": "progress",
            "comment": "- the installation's request id and phase, with the attempt while installing.",
            "text": "@param progress - the installation's request id and phase, with the attempt while installing."
          }
        ],
        "jsDoc": "/**\n * An installation moved between its Host phases. `installing` is announced once per registry the\n * installation asks, with the attempt's registry and position; `cancelling` and `applying` once.\n * @mode emit\n * @param progress - the installation's request id and phase, with the attempt while installing.\n */",
        "name": "plugin-manager/install-state",
        "mode": "emit",
        "signature": "'plugin-manager/install-state'(progress: PluginInstallProgress): void"
      }
    ],
    "objects": []
  },
}
